version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build \
                  --pull \
                  --build-arg ANSIBLE_VERSION=2.9.0 \
                  -t ksandermann/ansible:2.9.0 \
                  -f ansible/Dockerfile \
                  ./ansible
